GET http://localhost:8080/conta/all

###

POST http://localhost:8080/conta/save
Content-Type: application/json

{
    "id": null,
    "categoria": {
        "id": 1
    },
    "tipo": false,
    "data": "2023-12-30",
    "descricao": "Higiene",
    "valor": 250,
    "destinoOrigem": "Mercado",
    "status": false
}

