GET http://localhost:8080/conta/all

###

POST http://localhost:8080/conta/save
Content-Type: application/json

{
    "id": null,
    "categoria": {
        "id": 1
    },
    "tipo": true,
    "data": "2023-12-30",
    "descricao": "Villefort",
    "valor": 450,
    "destinoOrigem": "Villefort",
    "status": true
}

